export let GET_STUDENT_PENDING = "GET_STUDENT_PENDING";
export let GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export let GET_STUDENT_ERROR = "GET_STUDENT_ERROR";

export let POST_STUDENT_PENDING = "POST_STUDENT_PENDING";
export let POST_STUDENT_SUCCESS = "POST_STUDENT_SUCCESS";
export let POST_STUDENT_ERROR = "POST_STUDENT_ERROR";

export let DELETE_STUDENT_PENDING = "DELETE_STUDENT_PENDING";
export let DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export let DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";

export let UPDATE_STUDENT_PENDING = "UPDATE_STUDENT_PENDING";
export let UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export let UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";